### PR TITLE
devDeps: reapply babel 7 upgrade

### PR DESCRIPTION
**Pull request by legobeat**
- Reapply of #24 and #28 
- Add peerDependency `@babel/runtime@^7.0.0`

#### Blocking
- #35

#### Blocked by
- [x] #33 
  - [x] #32

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore update-browserslist-db@1.0.13
    
shell access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore rxjs@6.6.7

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore @nicolo-ribaudo/eslint-scope-5-internals@5.1.1-v1
    @SocketSecurity ignore eslint-module-utils@2.8.0
    @SocketSecurity ignore for-each@0.3.3
    @SocketSecurity ignore pathval@1.1.1
    @SocketSecurity ignore is-async-function@2.0.0
    @SocketSecurity ignore anymatch@3.1.3
    @SocketSecurity ignore convert-source-map@2.0.0
    @SocketSecurity ignore unicode-canonical-property-names-ecmascript@2.0.0
    @SocketSecurity ignore unicode-match-property-ecmascript@2.0.0
    @SocketSecurity ignore loupe@2.3.7
    @SocketSecurity ignore ms@2.1.2
    @SocketSecurity ignore check-error@1.0.3


new author, no readme ok

**Comment by legobeat** [comment]
@SocketSecurity ignore debug@3.2.6
    @SocketSecurity ignore fsevents@2.1.3
    @SocketSecurity ignore flat@4.1.1

legacy via mocha

**Comment by legobeat** [comment]
@SocketSecurity ignore semver@6.3.1

bin script confusion ok; `semver@^5.5.1` still pulled in via `eslint`; upgraded to v6 in `eslint@6.1.0`.

**Review by kumavis — APPROVED** [review]

**Pull request merged**
